// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhocdqtqohcnxrxhczhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ob2NkcXRxb2hjbnhyeGhjemh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTg3ODIsImV4cCI6MjA1ODMzNDc4Mn0.QF1OfYEBYgthIM961E65UaADVYZv75hcCCPs9p2iEjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);